version: "3"
services:
    back:
        image: registry.heroku.com/epoc-backend-testing/web:latest
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_PASSWORD=password
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/epoc
            - SPRING_DATASOURCE_USERNAME=user
            - FIREBASE_SERVICE_ACCOUNT_JSON=${FIREBASE_SERVICE_ACCOUNT_JSON}
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=${JWT_ISSUER}
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
    postgres:
        image: ghcr.io/three-consulting/epoc-mock-db:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=epoc
