version: "3"
services:
    back:
        image: ghcr.io/three-consulting/epoc-backend:latest
        ports:
            - "8080:8080"
        environment:
            - SPRING_DATASOURCE_PASSWORD=password
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/epoc
            - SPRING_DATASOURCE_USERNAME=user
            - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=${JWT_ISSUER}
    postgres:
        image: ghcr.io/three-consulting/epoc-db:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=epoc
