/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/project': {
        get: operations['getAllProject'];
        put: operations['updateProjectForId'];
        post: operations['createProject'];
    };
    '/employee': {
        put: operations['updateEmployeeForId'];
        post: operations['createEmployee'];
    };
    '/customer': {
        put: operations['updateCustomerForId'];
        post: operations['createCustomer'];
    };
    '/project/{projectId}': {
        get: operations['getCustomerForId'];
        delete: operations['deleteCustomerForId'];
    };
    '/employee/{employeeId}': {
        get: operations['getCustomerForId_1'];
        delete: operations['deleteCustomerForId_1'];
    };
    '/customer/{customerId}': {
        get: operations['getCustomerForId_2'];
        delete: operations['DeleteCustomerForId'];
    };
}

export interface components {
    schemas: {
        CustomerDTO: {
            id?: number;
            name: string;
            description?: string;
            created?: string;
            updated?: string;
            enabled?: boolean;
        };
        EmployeeDTO: {
            id?: number;
            first_name?: string;
            last_name?: string;
            email?: string;
            start_date?: string;
            created?: string;
            updated?: string;
        };
        ProjectDTO: {
            id?: number;
            name: string;
            description?: string;
            startDate?: string;
            endDate?: string;
            customer?: components['schemas']['CustomerDTO'];
            managingEmployee?: components['schemas']['EmployeeDTO'];
            status?: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
            created?: string;
            updated?: string;
        };
        Customer: {
            name?: string;
            description?: string;
            created?: string;
            updated?: string;
            enabled?: boolean;
            id?: number;
        };
        Employee: {
            first_name?: string;
            last_name?: string;
            email?: string;
            start_date?: string;
            created?: string;
            updated?: string;
            id?: number;
        };
        Project: {
            customer?: components['schemas']['Customer'];
            managingEmployee?: components['schemas']['Employee'];
            name?: string;
            description?: string;
            startDate?: string;
            endDate?: string;
            created?: string;
            updated?: string;
            status?: 'ACTIVE' | 'INACTIVE' | 'ARCHIVED';
            id?: number;
        };
    };
}

export interface operations {
    getAllProject: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['Project'][];
                };
            };
        };
    };
    updateProjectForId: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['ProjectDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ProjectDTO'];
            };
        };
    };
    createProject: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['ProjectDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['ProjectDTO'];
            };
        };
    };
    updateEmployeeForId: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['EmployeeDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['EmployeeDTO'];
            };
        };
    };
    createEmployee: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['EmployeeDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['EmployeeDTO'];
            };
        };
    };
    updateCustomerForId: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['CustomerDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CustomerDTO'];
            };
        };
    };
    createCustomer: {
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['CustomerDTO'];
                };
            };
        };
        requestBody: {
            content: {
                'application/json': components['schemas']['CustomerDTO'];
            };
        };
    };
    getCustomerForId: {
        parameters: {
            path: {
                projectId: number;
            };
        };
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['ProjectDTO'];
                };
            };
        };
    };
    deleteCustomerForId: {
        parameters: {
            path: {
                projectId: number;
            };
        };
        responses: {
            /** OK */
            200: unknown;
        };
    };
    getCustomerForId_1: {
        parameters: {
            path: {
                employeeId: number;
            };
        };
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['EmployeeDTO'];
                };
            };
        };
    };
    deleteCustomerForId_1: {
        parameters: {
            path: {
                employeeId: number;
            };
        };
        responses: {
            /** OK */
            200: unknown;
        };
    };
    getCustomerForId_2: {
        parameters: {
            path: {
                customerId: number;
            };
        };
        responses: {
            /** OK */
            200: {
                content: {
                    '*/*': components['schemas']['CustomerDTO'];
                };
            };
        };
    };
    DeleteCustomerForId: {
        parameters: {
            path: {
                customerId: number;
            };
        };
        responses: {
            /** OK */
            200: unknown;
        };
    };
}

export interface external {}
