/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/timesheet": {
    put: operations["updateTimesheetForId"];
    post: operations["createTimesheet"];
  };
  "/project": {
    get: operations["getAllProjects"];
    put: operations["updateProjectForId"];
    post: operations["createProject"];
  };
  "/employee": {
    get: operations["getAllEmployees"];
    put: operations["updateEmployeeForId"];
    post: operations["createEmployee"];
  };
  "/customer": {
    get: operations["getAllCustomers"];
    put: operations["updateCustomerForId"];
    post: operations["createCustomer"];
  };
  "/timesheet/{timesheetId}": {
    get: operations["getTimesheetForId"];
    delete: operations["deleteTimesheetForId"];
  };
  "/project/{projectId}": {
    get: operations["getProjectForId"];
    delete: operations["deleteProjectForId"];
  };
  "/employee/{employeeId}": {
    get: operations["getEmployeeForId"];
    delete: operations["deleteEmployeeForId"];
  };
  "/customer/{customerId}": {
    get: operations["getCustomerForId"];
    delete: operations["deleteCustomerForId"];
  };
}

export interface components {
  schemas: {
    CustomerDTO: {
      id?: number;
      name: string;
      description?: string;
      created?: string;
      updated?: string;
      enabled?: boolean;
    };
    EmployeeDTO: {
      id?: number;
      first_name?: string;
      last_name?: string;
      email?: string;
      start_date?: string;
      created?: string;
      updated?: string;
    };
    ProjectDTO: {
      id?: number;
      name: string;
      description?: string;
      startDate?: string;
      endDate?: string;
      customer?: components["schemas"]["CustomerDTO"];
      managingEmployee?: components["schemas"]["EmployeeDTO"];
      status?: "ACTIVE" | "INACTIVE" | "ARCHIVED";
      created?: string;
      updated?: string;
    };
    TimesheetDTO: {
      id?: number;
      name: string;
      description?: string;
      allocation?: number;
      project?: components["schemas"]["ProjectDTO"];
      employee?: components["schemas"]["EmployeeDTO"];
      created?: string;
      updated?: string;
    };
  };
}

export interface operations {
  updateTimesheetForId: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TimesheetDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TimesheetDTO"];
      };
    };
  };
  createTimesheet: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TimesheetDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TimesheetDTO"];
      };
    };
  };
  getAllProjects: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"][];
        };
      };
    };
  };
  updateProjectForId: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDTO"];
      };
    };
  };
  createProject: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectDTO"];
      };
    };
  };
  getAllEmployees: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["EmployeeDTO"][];
        };
      };
    };
  };
  updateEmployeeForId: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["EmployeeDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeDTO"];
      };
    };
  };
  createEmployee: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["EmployeeDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmployeeDTO"];
      };
    };
  };
  getAllCustomers: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDTO"][];
        };
      };
    };
  };
  updateCustomerForId: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerDTO"];
      };
    };
  };
  createCustomer: {
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDTO"];
        };
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CustomerDTO"];
      };
    };
  };
  getTimesheetForId: {
    parameters: {
      path: {
        timesheetId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["TimesheetDTO"];
        };
      };
    };
  };
  deleteTimesheetForId: {
    parameters: {
      path: {
        timesheetId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
  getProjectForId: {
    parameters: {
      path: {
        projectId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
  };
  deleteProjectForId: {
    parameters: {
      path: {
        projectId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
  getEmployeeForId: {
    parameters: {
      path: {
        employeeId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["EmployeeDTO"];
        };
      };
    };
  };
  deleteEmployeeForId: {
    parameters: {
      path: {
        employeeId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
  getCustomerForId: {
    parameters: {
      path: {
        customerId: number;
      };
    };
    responses: {
      /** OK */
      200: {
        content: {
          "*/*": components["schemas"]["CustomerDTO"];
        };
      };
    };
  };
  deleteCustomerForId: {
    parameters: {
      path: {
        customerId: number;
      };
    };
    responses: {
      /** OK */
      200: unknown;
    };
  };
}

export interface external {}
