// eslint-disable-next-line @typescript-eslint/no-var-requires
const readline = require("readline")

// eslint-disable-next-line id-length
const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
    terminal: false,
})

const generateFieldMetadata = (field, required) =>
    `${field}: {required: ${required.includes(field)}}`

const generateSchemaMetadata = (type, schema) => {
    const fields = Object.keys(schema.properties)
    const { required } = schema
    return `export const ${type[0].toLowerCase() + type.slice(1)}FieldMetadata: Record<string, FieldMetadata> = {
        ${fields
        .map((field) => `${generateFieldMetadata(field, required)}`)
        .join(", ")}}`
}

rl.on("line", (data) => {
    const schema = JSON.parse(data)
    const types = schema.components.schemas
    const schemaMetadata = Object.keys(types)
        .map((type) => generateSchemaMetadata(type.replace("DTO", ""), types[type]))
        .join("\n\n")
    const out = `
  // This file is automatically generated, do not edit
  export type FieldMetadata = { required: boolean }

  ${schemaMetadata}`
    // eslint-disable-next-line no-console
    console.log(out)
})
