name: Dev

on:
  push:
    branches:
      - google-cloud
  workflow_dispatch:

env:
  PROJECT_ID: epoc-auth-dev-361109 # Google Cloud project id
  FAR_LOCATION: europe-north1 # Artifact Registry location
  REPOSITORY: epoc-dev-container-repository # Artifact Registry repository name
  SERVICE: epoc-frontend-dev # Cloud Run service name
  REGION: europe-north1 # Cloud Run service region


jobs:
  run_tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS_DEV }}
          token_format: 'access_token'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: '${{ env.REGION }}-docker.pkg.dev'
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'
      
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY_DEV }}
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN_DEV }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL_DEV }}
            NEXT_PUBLIC_GOOGLE_APIKEY=${{ secrets.NEXT_PUBLIC_GOOGLE_APIKEY_DEV }}
          context: .
          push: true
          tags: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
