name: housekeeping
on:
    push:
        branches:
            - '**'
    pull_request:
        types:
            - opened
            - synchronize
            - reopened
jobs:
    tsc-and-format:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies and run tsc and prettier
              run: |
                  yarn install
                  yarn run type-check
                  yarn prettier --check .
