name: housekeeping
on: [push, pull_request]
jobs:
    tsc-and-format:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: '14'
            - name: Install dependencies
              run: |
                  yarn install
                  yarn run type-check
                  yarn prettier --check .
