name: Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies and run checks
        run: |
          yarn install
          yarn run type-check
          yarn prettier --check .
          yarn eslint .
          yarn test
   
      - name: Check types in dev
        id: validate_types_dev
        run: |
          yarn openapi-typescript https://epoc-backend-testing.herokuapp.com/docs --output dev.ts
          export DEV_DIFF="$(diff dev.ts lib/types/api.ts)"
          echo "DEV_DIFF<<EOF" >> $GITHUB_ENV
          echo "$DEV_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check types in prod
        id: validate_types_prod
        run: |
          yarn openapi-typescript https://epoc-backend.herokuapp.com/docs --output prod.ts
          export PROD_DIFF="$(diff prod.ts lib/types/api.ts)"
          echo "PROD_DIFF<<EOF" >> $GITHUB_ENV
          echo "$PROD_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV


      - name: Find old dev type validation comment
        uses: peter-evans/find-comment@v2
        id: dev-types
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: DEV type validation result

      - name: Find old dev type validation comment
        uses: peter-evans/find-comment@v2
        id: prod-types
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PROD type validation result

      - name: Comment results of dev type validations
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.dev-types.outputs.comment-id }}
          edit-mode: replace
          body: |
            DEV type validation result
            ```diff
            ${{ env.DEV_DIFF }}
            ```

      - name: Comment results of prod type validations
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.prod-types.outputs.comment-id }}
          edit-mode: replace
          body: |
            PROD type validation result
            ```diff
            ${{ env.PROD_DIFF }}
            ```
