name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  run_tests_and_build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies and run checks
        run: |
          yarn install
          yarn run type-check
          yarn prettier --check .
          yarn eslint .
   
      - name: Create nginx conf file
        env:
          NGINX_SERVER_NAME: epoc-frontend.run.app
        run: envsubst '$NGINX_SERVER_NAME' < nginx.conf.tmpl > nginx.conf
      
      -  name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2

      - name: Build image to artifact registry
        uses: docker/build-push-action@v4
        with:
          build-args: |
            NEXT_PUBLIC_FIREBASE_API_KEY=asd
            NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=asd
            NEXT_PUBLIC_API_URL=http://localhost
            NEXT_PUBLIC_GOOGLE_APIKEY=asd
          context: .
          file: Dockerfile
          no-cache: false
          push: false

      - name: Check types in dev
        if: github.actor != 'dependabot[bot]'
        id: validate_types_dev
        run: |
          yarn openapi-typescript https://epoc-backend-dev-ka3fwwycka-lz.a.run.app/docs --output dev.ts
          export DEV_DIFF="$(diff dev.ts lib/types/api.ts)"
          echo "DEV_DIFF<<EOF" >> $GITHUB_ENV
          echo "$DEV_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check types in prod
        if: github.actor != 'dependabot[bot]'
        id: validate_types_prod
        run: |
          yarn openapi-typescript https://epoc-backend.herokuapp.com/docs --output prod.ts
          export PROD_DIFF="$(diff prod.ts lib/types/api.ts)"
          echo "PROD_DIFF<<EOF" >> $GITHUB_ENV
          echo "$PROD_DIFF" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Find old dev type validation comment
        if: github.actor != 'dependabot[bot]'
        uses: peter-evans/find-comment@v2
        id: dev-types
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: DEV type validation result

      - name: Find old dev type validation comment
        if: github.actor != 'dependabot[bot]'
        uses: peter-evans/find-comment@v2
        id: prod-types
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: PROD type validation result

      - name: Comment results of dev type validations
        if: github.actor != 'dependabot[bot]'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.dev-types.outputs.comment-id }}
          edit-mode: replace
          body: |
            DEV type validation result
            ```diff
            ${{ env.DEV_DIFF }}
            ```

      - name: Comment results of prod type validations
        if: github.actor != 'dependabot[bot]'
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.prod-types.outputs.comment-id }}
          edit-mode: replace
          body: |
            PROD type validation result
            ```diff
            ${{ env.PROD_DIFF }}
            ```

  automerge:
    needs: run_tests_and_build
    permissions:
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge dependabot PR
        uses: fastify/github-action-merge-dependabot@v3
        with:
          target: minor
          skip-commit-verification: true
